// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Aprico.Messaging.ServiceBus.Outbox;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aprico.Migrations
{
	[DbContext(typeof(OutboxInstallerDbContext))]
	[Migration("20250405103411_CreateStoredProcedures")]
	partial class CreateStoredProcedures
	{
		/// <inheritdoc />
		[SuppressMessage("ReSharper", "StringLiteralTypo")]
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "9.0.3")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("Aprico.Messaging.ServiceBus.Outbox.Message", b =>
			{
				b.Property<Guid>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("uniqueidentifier")
					.HasColumnOrder(0);

				b.Property<string>("Body")
					.IsRequired()
					.HasColumnType("nvarchar(max)")
					.HasColumnOrder(3);

				b.Property<string>("Headers")
					.IsRequired()
					.HasColumnType("nvarchar(max)")
					.HasColumnOrder(2);

				b.Property<string>("Subject")
					.IsRequired()
					.HasMaxLength(256)
					.HasColumnType("nvarchar(256)")
					.HasColumnOrder(1);

				b.Property<DateTimeOffset>("Timestamp")
					.HasColumnType("datetimeoffset(7)")
					.HasColumnOrder(4);

				b.HasKey("Id");

				b.ToTable("Messages", "outbox");
			});
#pragma warning restore 612, 618
		}
	}
}
